/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"
#include "nsIDownloadManagerUI.idl"

interface nsIDOMWindowInternal;

[scriptable, uuid(bfac4b43-ddc9-4910-abb8-3287377e48e2)]
interface nsIKDownloadManagerUI : nsIDownloadManagerUI
{
  attribute nsIDOMWindowInternal recentWindow;
  void showManager([optional] in nsIInterfaceRequestor aWindowContext,
                    [optional] in unsigned long aID,
                    [optional] in short aReason);
  void showProgress([optional] in nsIInterfaceRequestor aWindowContext,
                     [optional] in unsigned long aID,
                     [optional] in short aReason);
};
